import '../templates/styles/leader.css';
import '../templates/styles/vote.css';
import '../templates/styles/chart.css';
import '../templates/styles/diagram.css';
import '../templates/styles/activity.css';
import '../templates/styles/font.css';
// import '../templates/fonts/Roboto-Medium.ttf';
// import '../templates/fonts/Roboto-Bold.ttf';
// import '../templates/fonts/Roboto-Regular.ttf';
require('../templates/renderTemplate.js');
require('../templates/main.js');